/** Shared catalog copy for seed + client fallbacks (CommonJS). */

const HERO_SLIDES = [
  {
    imageUrl:
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1920&q=90&auto=format&fit=crop',
    videoUrl: null,
    title: 'Premium Cotton T-Shirts',
    subtitle: 'Merry Berry — Lahore, Pakistan',
    ctaLabel: 'Shop T-Shirts',
    ctaHref: '/shop?category=basic-t-shirt',
    sortOrder: 0,
    active: true,
  },
  {
    imageUrl:
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1920&q=90&auto=format&fit=crop',
    videoUrl: null,
    title: 'Baggy Jeans & Street Denim',
    subtitle: 'Dress with Confidence',
    ctaLabel: 'Shop Jeans',
    ctaHref: '/shop?category=baggy-jeans',
    sortOrder: 1,
    active: true,
  },
  {
    imageUrl:
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=1920&q=90&auto=format&fit=crop',
    videoUrl: null,
    title: 'Winter Hoodies & Jackets',
    subtitle: 'Stay warm in style',
    ctaLabel: 'Winter Collection',
    ctaHref: '/shop?category=hoodie',
    sortOrder: 2,
    active: true,
  },
  {
    imageUrl:
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1920&q=90&auto=format&fit=crop',
    videoUrl: null,
    title: 'Graphic Tees & Custom Print',
    subtitle: 'Your design, our quality',
    ctaLabel: 'Explore Graphics',
    ctaHref: '/shop?category=graphic-tee',
    sortOrder: 3,
    active: true,
  },
];

const PRODUCT_NAMES = {
  'baggy-jeans': [
    'Merry Berry Loose Baggy Denim',
    'Street Flex Wide Leg Jean',
    'Urban Drop Baggy Blue',
    'Classic Relaxed Fit Denim',
    'Lahore Street Baggy Jean',
    'Deep Indigo Baggy Fit',
    'Comfort Stretch Baggy',
    'Vintage Wash Baggy Denim',
    'Night Rider Loose Jean',
    'Essential Black Baggy',
  ],
  'cargo-jeans': [
    'Merry Berry Multi-Pocket Cargo',
    'Tactical Street Cargo Jean',
    'Olive Utility Cargo Denim',
    'Classic Side Pocket Cargo',
    'Urban Explorer Cargo',
    'Heavy Duty Cargo Jean',
    'Slim Cargo Street Fit',
    'Sand Tone Cargo Denim',
    'Adventure Flex Cargo',
    'Premium 6-Pocket Cargo',
  ],
  'straight-fit': [
    'Merry Berry Straight Fit Denim',
    'Clean Cut Straight Jean',
    'Office Ready Straight Denim',
    'Midnight Straight Fit',
    'Classic Blue Straight Jean',
    'Smart Casual Straight Denim',
    'Everyday Straight Fit',
    'Stone Wash Straight Jean',
    'Sharp Line Straight Denim',
    'Essential Straight Blue',
  ],
  tracksuit: [
    'Merry Berry Fleece Tracksuit',
    'Sport Flex Jogger Set',
    'Urban Comfort Tracksuit',
    'Classic Two-Piece Track Set',
    'Premium Cotton Tracksuit',
    'Street Runner Track Set',
    'Zip Hoodie Track Combo',
    'Athleisure Track Suit',
    'Winter Warm Tracksuit',
    'Berry Logo Track Set',
  ],
  trouser: [
    'Merry Berry Slim Chino Trouser',
    'Formal Flex Trouser',
    'Office Smart Trouser',
    'Stretch Comfort Trouser',
    'Classic Beige Chino',
    'Charcoal Slim Trouser',
    'Everyday Cotton Trouser',
    'Premium Tailored Trouser',
    'Casual Fit Chino',
    'Essential Black Trouser',
  ],
  'basic-t-shirt': [
    'Merry Berry Classic Cotton Tee',
    'Essential White Round Neck',
    'Premium Black Basic Tee',
    'Soft Touch Grey Tee',
    'Lahore Street Cotton Tee',
    'Berry Logo Minimal Tee',
    'Everyday Comfort Fit Tee',
    'Pure Cotton Crew Neck',
    'Slim Fit Basic White',
    'Midnight Black Essential Tee',
  ],
  polo: [
    'Merry Berry Pique Polo Shirt',
    'Classic Navy Polo',
    'Premium Cotton Polo',
    'Berry Embroidered Polo',
    'Summer Breeze Polo',
    'Smart Casual White Polo',
    'Urban Fit Polo Shirt',
    'Contrast Collar Polo',
    'Essential Black Polo',
    'Lahore Classic Polo',
  ],
  'over-sized': [
    'Merry Berry Oversized Drop Tee',
    'Street Box Fit T-Shirt',
    'Relaxed Oversized Cotton',
    'Urban Loose Fit Tee',
    'Heavy Cotton Oversized',
    'Minimal Oversized White',
    'Berry Street Oversized',
    'Baggy Fit Graphic Base Tee',
    'Cloud Soft Oversized Tee',
    'Essential Oversized Black',
  ],
  'graphic-tee': [
    'Merry Berry Street Graphic Tee',
    'Lahore Vibes Print Tee',
    'Berry Logo Statement Tee',
    'Urban Art Graphic Shirt',
    'Vintage Wash Graphic Tee',
    'Bold Typography Tee',
    'Retro Street Print Tee',
    'Minimal Line Art Tee',
    'Pakistan Pride Graphic Tee',
    'Night City Print Tee',
  ],
  'formal-shirt': [
    'Merry Berry Formal Cotton Shirt',
    'Office Classic White Shirt',
    'Slim Fit Formal Blue',
    'Premium Non-Iron Shirt',
    'Business Smart Formal',
    'Linen Blend Formal Shirt',
    'Essential Sky Blue Formal',
    'Tailored Fit Dress Shirt',
    'Charcoal Formal Shirt',
    'Executive Cotton Shirt',
  ],
  'long-shirt': [
    'Merry Berry Modest Long Shirt',
    'Flowing Cotton Long Top',
    'Elegant Long Kurti Shirt',
    'Soft Drape Long Shirt',
    'Classic Embroidered Long',
    'Comfort Fit Long Shirt',
    'Pastel Long Cotton Top',
    'Premium Lawn Long Shirt',
    'Everyday Modest Long',
    'Berry Trim Long Shirt',
  ],
  'night-suit': [
    'Merry Berry Cotton Night Suit',
    'Soft Fleece Night Suit',
    'Kids Cozy Night Set',
    'Floral Print Night Suit',
    'Winter Warm Night Suit',
    'Premium Pajama Set',
    'Comfort Lounge Night Suit',
    'Berry Print Night Set',
    'Family Cotton Night Suit',
    'Essential Night Wear Set',
  ],
  'kids-jeans': [
    'Merry Berry Kids Stretch Jean',
    'Junior Baggy Denim',
    'Kids Comfort Fit Jean',
    'Playproof Kids Denim',
    'Soft Wash Kids Jean',
    'School Ready Kids Denim',
    'Flexible Kids Blue Jean',
    'Kids Slim Denim',
    'Berry Kids Street Jean',
    'Essential Kids Jean',
  ],
  'kids-t-shirts': [
    'Merry Berry Kids Cotton Tee',
    'Junior Graphic Fun Tee',
    'Kids Berry Logo Tee',
    'Soft Kids Round Neck',
    'Playtime Cotton Tee',
    'Kids Color Pop Tee',
    'School Basic Kids Tee',
    'Kids Dinosaur Print Tee',
    'Comfort Kids Stripe Tee',
    'Essential Kids White Tee',
  ],
  'denim-jacket': [
    'Merry Berry Classic Denim Jacket',
    'Vintage Wash Denim Jacket',
    'Street Layer Denim Jacket',
    'Distressed Blue Denim Jacket',
    'Essential Black Denim Jacket',
    'Sherpa Lined Denim Jacket',
    'Slim Fit Denim Jacket',
    'Urban Trucker Denim',
    'Berry Patch Denim Jacket',
    'Premium Raw Denim Jacket',
  ],
  hoodie: [
    'Merry Berry Fleece Hoodie',
    'Street Comfort Pullover',
    'Premium Cotton Hoodie',
    'Berry Logo Hoodie',
    'Oversized Cozy Hoodie',
    'Zip-Up Urban Hoodie',
    'Winter Warm Hoodie',
    'Minimal Black Hoodie',
    'Soft Touch Grey Hoodie',
    'Essential Navy Hoodie',
  ],
  'puffer-jacket': [
    'Merry Berry Lightweight Puffer',
    'Winter Shield Puffer Jacket',
    'Urban Quilted Puffer',
    'Packable Travel Puffer',
    'Matte Black Puffer Jacket',
    'High Collar Puffer',
    'Berry Street Puffer',
    'Premium Down-Style Puffer',
    'Frost Guard Puffer',
    'Essential Olive Puffer',
  ],
  zipper: [
    'Merry Berry Full Zip Fleece',
    'Street Zip-Up Jacket',
    'Sport Flex Zip Jacket',
    'Premium Zip Sweat Jacket',
    'Urban Layer Zip Top',
    'Comfort Cotton Zip Jacket',
    'Berry Logo Zip Fleece',
    'Winter Zip Warm Jacket',
    'Essential Black Zip',
    'Active Zip Track Jacket',
  ],
};

module.exports = { HERO_SLIDES, PRODUCT_NAMES };
